"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

const services = [["The Classic", "$34"], ["Cut + Beard", "$48"], ["The Full Service", "$62"]];

export default function VintageBarbershopConcept() {
  const [selected, setSelected] = useState("The Classic");
  return <main className="min-h-screen bg-[#171512] text-[#f2eadc]">
    <header className="absolute inset-x-0 top-0 z-20 border-b border-white/15"><div className="mx-auto flex h-20 max-w-[1400px] items-center justify-between px-5 sm:px-10"><strong className="font-serif text-xl tracking-[0.15em]">THE VINTAGE</strong><nav className="hidden gap-7 text-xs uppercase tracking-[0.14em] md:flex"><Link href="#services">Services</Link><Link href="#story">Our story</Link><Link href="#book">Book</Link></nav><Link href="/work/vintage-barbershop" className="rounded-full border border-white/30 px-4 py-2 text-[10px] font-bold uppercase tracking-widest">Case study</Link></div></header>
    <section className="relative grid min-h-screen items-end overflow-hidden"><Image src="/images/portfolio/barber/hero.jpg" alt="Vintage barbershop interior" fill priority sizes="100vw" className="object-cover opacity-55"/><div className="absolute inset-0 bg-gradient-to-t from-[#171512] via-transparent to-[#171512]/55"/><div className="relative mx-auto w-full max-w-[1400px] px-5 pb-16 pt-32 sm:px-10 lg:pb-24"><p className="text-xs font-bold uppercase tracking-[0.3em] text-[#cfaa71]">Established with intention</p><h1 className="mt-5 max-w-5xl font-serif text-[clamp(4rem,10vw,9rem)] leading-[0.82] tracking-[-0.055em]">Sharp cuts.<br/><em className="font-light text-[#cfaa71]">Old soul.</em></h1><div className="mt-10 flex flex-wrap gap-3"><Link href="#book" className="bg-[#cfaa71] px-6 py-3 text-xs font-bold uppercase tracking-widest text-[#171512]">Reserve a chair</Link><Link href="#services" className="border border-white/35 px-6 py-3 text-xs font-bold uppercase tracking-widest">View services</Link></div></div></section>
    <section id="services" className="mx-auto grid max-w-[1400px] gap-12 px-5 py-20 sm:px-10 lg:grid-cols-[0.8fr_1.2fr] lg:py-28"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#cfaa71]">The essentials</p><h2 className="mt-5 font-serif text-5xl leading-none sm:text-7xl">Good work<br/>takes time.</h2></div><div className="divide-y divide-white/15 border-y border-white/15">{services.map(([name, price], index) => <button key={name} onClick={() => setSelected(name)} className="flex w-full items-center justify-between py-7 text-left transition hover:px-3 hover:text-[#cfaa71]"><span><small className="mr-6 text-white/35">0{index + 1}</small><strong className="font-serif text-2xl font-normal">{name}</strong></span><span>{price}</span></button>)}</div></section>
    <section id="story" className="grid bg-[#eee5d6] text-[#221e19] lg:grid-cols-2"><div className="relative min-h-[480px]"><Image src="/images/portfolio/barber/feature-2.jpg" alt="Barber at work" fill sizes="(max-width: 1023px) 100vw, 50vw" className="object-cover"/></div><div className="flex flex-col justify-center p-8 sm:p-14 lg:p-20"><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#8f623c]">Craft over hurry</p><h2 className="mt-5 font-serif text-5xl leading-none sm:text-7xl">A neighborhood ritual.</h2><p className="mt-7 max-w-lg text-base leading-7 text-[#5d5145]">Classic technique, straightforward conversation, and a chair you can settle into. The atmosphere is nostalgic; the service is anything but dated.</p></div></section>
    <section id="book" className="mx-auto max-w-4xl px-5 py-20 text-center sm:px-10 lg:py-28"><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#cfaa71]">Your chair is ready</p><h2 className="mt-5 font-serif text-5xl sm:text-7xl">Book {selected}.</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-6 text-white/55">This local portfolio prototype demonstrates the booking direction. No appointment or information is submitted.</p><button className="mt-8 bg-[#cfaa71] px-8 py-4 text-xs font-bold uppercase tracking-widest text-[#171512]">Choose a time</button></section>
  </main>;
}
